import assert from "node:assert/strict";
import test from "node:test";
import { summarizeLocalMilestones, summarizePublicMilestones } from "../dist/index.js";
import { current, followup, reflection, row } from "./fixtures.js";

test("local reflection and later comparable negative finding are useful progress without an ability benefit", () => {
  const result = summarizeLocalMilestones([followup(), reflection()]);
  assert.equal(result.reflection, "recorded");
  assert.equal(result.later_comparable_outcome, "recorded");
  assert.deepEqual(result.retained_outcomes, ["regressed"]);
  assert.equal(result.quality, "floor_met_no_critical_regression");
  assert.equal(JSON.stringify(result).includes("TEST_ONLY_TASK"), false);
  assert.equal("score" in result, false);
  assert.equal("count" in result, false);
});
test("quality failure remains visible and never implies an improvement badge", () => {
  const negative = followup(); negative.quality_floor = "not_met"; negative.critical_regression = "observed";
  const result = summarizeLocalMilestones([reflection(), negative]);
  assert.equal(result.later_comparable_outcome, "recorded");
  assert.equal(result.quality, "regression_or_floor_failure");
  assert.deepEqual(result.retained_outcomes, ["regressed"]);
});
for (const change of ["copy", "revision_only", "unchanged", "unknown"] as const) {
  test(`${change} cannot establish reflection or later progress`, () => {
    assert.equal(summarizeLocalMilestones([{ ...reflection(), change }]).reflection, "not_established");
    const result = summarizeLocalMilestones([reflection(), { ...followup(), change }]);
    assert.equal(result.later_comparable_outcome, "not_established");
  });
}
for (const edit of [
  { sequence: 1 }, { sequence: 0 }, { task_key: "TEST_OTHER_TASK" }, { equivalence_key: "TEST_OTHER_EQUIVALENCE" },
  { comparison: "unknown" as const }, { evidence_available: false }, { content_origin: "synthetic" as const },
  { outcome: "not_measured" as const }, { outcome: "insufficient_evidence" as const },
]) test(`follow-up requires later comparable actual evidence: ${JSON.stringify(edit)}`, () => {
  assert.equal(summarizeLocalMilestones([reflection(), { ...followup(), ...edit }]).later_comparable_outcome, "not_established");
});
test("duplicates and volume produce identical summary, with no token or spend inputs", () => {
  const original = summarizeLocalMilestones([reflection(), followup()]);
  const repeated = summarizeLocalMilestones(Array.from({ length: 10 }, () => [reflection(), followup()]).flat());
  assert.deepEqual(original, repeated);
  assert.equal(summarizeLocalMilestones([{ ...reflection(), model_tokens: 10000 } as never]).state, "invalid_input");
});
test("public evidence summary remains self-reported and requires an observed comparable follow-up", () => {
  const record = row(1, 125);
  record.candidate.evidence.comparison = "observational_followup";
  const result = summarizePublicMilestones([record], current);
  assert.equal(result.reflection, "recorded");
  assert.equal(result.later_comparable_outcome, "recorded");
  assert.equal(result.evidence_label, "public_self_reported_evidence");
  assert.deepEqual(result.retained_outcomes, ["regressed"]);
  assert.equal(JSON.stringify(result).includes(record.public_id), false);
  record.capability_evidence!.distinct_task_band = "five_plus";
  assert.deepEqual(summarizePublicMilestones([record, record], current), result);
});
test("public badges cannot be generated by revision, large task bands, agent volume or benchmark met alone", () => {
  const record = row();
  record.capability_evidence!.change = "revision_only";
  record.capability_evidence!.distinct_task_band = "five_plus";
  assert.equal(summarizePublicMilestones([record], current).reflection, "not_established");
  record.capability_evidence!.change = "initial";
  const result = summarizePublicMilestones([record], current);
  assert.equal(result.reflection, "recorded");
  assert.equal(result.later_comparable_outcome, "not_established");
});
test("withdrawal removes public milestones, while local progress remains independent of sharing", () => {
  const record = row(); record.status = "withdrawn";
  assert.equal(summarizePublicMilestones([record], current).state, "no_eligible_records");
  assert.equal(summarizeLocalMilestones([reflection(), followup()]).state, "available");
  assert.equal(summarizePublicMilestones([row()], { ...current, complete: false }).state, "current_snapshot_required");
});
